# Generated by Django 4.2 on 2023-04-15 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('comprovante', models.FileField(upload_to='comprovantes')),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('financas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financas.financas')),
                ('categoria', models.CharField(choices=[('Csa', 'Casa'), ('Edu', 'Educação'), ('Elt', 'Eletrônicos'), ('lzr', 'Lazer'), ('Sau', 'Saúde'), ('Sup', 'Supermercado'), ('Tpt', 'Transporte'), ('O', 'Outros')], max_length=20)),
            ],
            bases=('financas.financas',),
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('financas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financas.financas')),
                ('categoria', models.CharField(choices=[('Inv', 'Investimento'), ('Pst', 'Presente'), ('Prm', 'Prêmio'), ('Slr', 'Salário'), ('O', 'Outros')], max_length=20)),
            ],
            bases=('financas.financas',),
        ),
    ]
