# Generated by Django 4.2 on 2023-04-16 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Financas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
                ('data', models.DateField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('comprovante', models.FileField(upload_to='comprovantes')),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('financas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financas.financas')),
                ('categoria', models.CharField(choices=[('1', 'Casa'), ('2', 'Educação'), ('3', 'Eletrônicos'), ('4', 'Lazer'), ('5', 'Saúde'), ('6', 'Supermercado'), ('7', 'Transporte'), ('8', 'Outros')], max_length=20)),
            ],
            bases=('financas.financas',),
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('financas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financas.financas')),
                ('categoria', models.CharField(choices=[('1', 'Investimento'), ('2', 'Presente'), ('3', 'Prêmio'), ('4', 'Salário'), ('5', 'Outros')], max_length=20)),
            ],
            bases=('financas.financas',),
        ),
    ]
