# Generated by Django 4.2 on 2023-04-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financas',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
