# Generated by Django 4.2 on 2023-04-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Educação', 'Educação'), ('Eletrônicos', 'Eletrônicos'), ('Lazer', 'Lazer'), ('Saúde', 'Saúde'), ('Supermercado', 'Supermercado'), ('Transporte', 'Transporte'), ('Outros', 'Outros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('Investimento', 'Investimento'), ('Presente', 'Presente'), ('Prêmio', 'Prêmio'), ('Salário', 'Salário'), ('Outros', 'Outros')], max_length=20),
        ),
    ]
