# Generated by Django 4.2.1 on 2023-05-16 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_alter_despesa_categoria_alter_receita_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financas',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
